import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faUser,
  faLock,
  faCircleUser,
  faBars,
  faGaugeHigh,
  faSquarePollHorizontal,
  faUserGroup,
  faLayerGroup,
  faCircleQuestion,
  faCircleCheck,
  faUserPlus,
  faClock,
  faPlusCircle,
  faCircleMinus,
  faEdit,
  faPencil,
  faPlus,
  faSearch,
  faTrashAlt,
  faAngleDown,
  faCircleXmark,
  faPeopleGroup,
  faUserCheck,
  faList,
  faListCheck,
  faFileArrowDown,
  faTurnUp,
  faChartLine,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faUser,
  faLock,
  faCircleUser,
  faBars,
  faGaugeHigh,
  faSquarePollHorizontal,
  faUserGroup,
  faLayerGroup,
  faCircleQuestion,
  faCircleCheck,
  faUserPlus,
  faClock,
  faPlusCircle,
  faCircleMinus,
  faEdit,
  faPencil,
  faPlus,
  faSearch,
  faTrashAlt,
  faAngleDown,
  faCircleXmark,
  faPeopleGroup,
  faUserCheck,
  faList,
  faListCheck,
  faFileArrowDown,
  faTurnUp,
  faChartLine
);

export default FontAwesomeIcon;
